name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  GITHUB_TAG_NAME: 1.0.0

jobs:
  build:
    runs-on: windows-2016

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '[15.0,16.5)'
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Win32
      run: |
          cmd.exe /c buildwin.bat

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with: 
        name: freeswitch
        path: |
              Win32/Release/mod/*.dll
              Win32/Release/*.dll
              Win32/Release/*.exe
              Win32/Release/freeswitchcore.lib
              Win32/Release/conf
              Win32/Debug/mod/*.dll
              Win32/Debug/*.dll
              Win32/Debug/freeswitchcore.lib
              Win32/Debug/conf
              x64/Release/mod/*.dll
              x64/Release/*.dll
              x64/Release/freeswitchcore.lib
              x64/Release/conf
              x64/Debug/mod/*.dll
              x64/Debug/*.dll
              x64/Debug/freeswitchcore.lib
              x64/Debug/conf
